version: '3.7'

services:
  api:
    image: neural_search
    container_name: neural_search
    ports:
      - 8000:8000
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant:v1.2.2
    ports:
    - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
